title: ALPS Healthcare
url: https://www.alpshealthcare.com.sg
favicon: /images/alps, tagline, black, transparent, 1000x921.png
colors:
  primary-color: "#dc1931"
  secondary-color: "#ed9787"
  media-colors:
    - title: media-color-one
      color: "#836db1"
    - title: media-color-two
      color: "#9c8ac1"
    - title: media-color-three
      color: "#e8e5f3"
    - title: media-color-four
      color: "#9b9b9b"
    - title: media-color-five
      color: "#ffffff"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1nskbz02w25xt.amplifyapp.com
prod: https://master.d1nskbz02w25xt.amplifyapp.com
facebook-pixel: "267117415265946"
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics: ""
google_analytics_ga4: G-PBTDQNC1PD
linkedin-insights: ""
resources_name: resources
